version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: test
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
